spring.application.name=ecomm2
spring.profiles.active=dev

## DB connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm2
#spring.datasource.username=<db-username>
#spring.datasource.password=<db-password>
#spring.datasource.driver-class-name=org.postgresql.Driver

## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true