services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    mem_limit: 512m
    cpus: 1.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
